[package]
name = "maker-arm-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "maker_arm_rs"
crate-type = ["cdylib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
maker-arm = { path = "../../crates/maker-arm", features = ["socketcan"] }
maker-arm-protocol = { path = "../../crates/maker-arm-protocol" }
maker-arm-transport = { path = "../../crates/maker-arm-transport", features = ["socketcan"] }
pyo3 = { version = "0.24" }
